### ISSUE TITLE
ODPC: minimaal document versturen naar Registratiecomponent

### ISSUE THREAD

**Issue by felixcicatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#42]
_Als gebruiker wil ik dat een geupload document wordt opgeslagen in de ODRC, zodat deze later ook geraadpleegd kan worden door de burger in het ODBP._

**Acceptance criteria (what)**
 
- Documenten (#22) worden als onderdeel van de publicatie opgeslagen in het ODRC via de API. Zie [ODRC #19](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/19).
- De gebruiker ziet dat een document succesvol is geüpload en toegevoegd aan het ODRC (of niet).
- Wijzigingen van documenten worden eveneens verwerkt in het ODRC
- Documentatie van alle configuratie / environment variabelen met voorbeelden. In eerste instantie in installation.md bestand in de ODPC github repository

**Specific details (how)**
In #22 hebben we velden voor een minimaal document toegevoegd aan het publicatieformulier. In deze story gaan we de inhoud van deze velden naar de Registratiecomponent sturen.

Foutafhandeling: als het formulier kan niet worden opgeslagen, komt er een generieke foutmelding in het scherm en kan je het opnieuw proberen.

~~Als je sessie verlopen is, krijg je de optie om opnieuw in te loggen en het opnieuw te proberen (zonder dat je werk verliest).~~ (maken we een losse story voor aan)

**Test plan**

- Document na opslaan zichtbaar in de beheerinterface van de Registratiecomponent van Maykin, en het bestand is daar te downloaden

**Tasks**
- [x] Endpoint voor initialiseren document: aanpassen zodat het verzoek doorgestuurd word aan het ODRC, vergelijkbaar met hoe dat bij de publicatie gebeurt
- [x] Endpoint voor bijwerken document: aanpassen zodat het verzoek doorgestuurd word aan het ODRC
- [x] Endpoint voor ophalen documenten bij publicatie: aanpassen zodat het verzoek doorgestuurd word aan het ODRC
- [ ] ~~Endpoint voor ophalen specifiek document obv id: aanpassen zodat het verzoek doorgestuurd word aan het ODRC~~ (niet van toepassing)
- [x] Endpoint voor uploaden bestandsdeel: aanpassen zodat het verzoek doorgestuurd word aan het ODRC
  - BV: dit endpoint werkt obv multipart/form-data, niet obv json
- [x] Mock voor documenten opruimen

**Comment by MarcoKlerks** [comment]
Bevindingen:
1. Een document van 0 KB leidt tot problemen
2. ZIP-bestand wordt niet geaccepteerd.

Mondeling afgesproken dat fixes hiervoor worden meegenomen bij de volgende user story.

**Comment by nijmra** [comment]
> Bevindingen:
> 
> 1. Een document van 0 KB leidt tot problemen
> 2. ZIP-bestand wordt niet geaccepteerd.
> 
> Mondeling afgesproken dat fixes hiervoor worden meegenomen bij de volgende user story.

Zie #68
