### ISSUE TITLE
ODPC: Publicaties en documenten ophalen, publiceren en intrekken uit het ODRC

### ISSUE THREAD

**Issue by mstokericatt** [GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#68]
Als gebruiker wil ik 'echte' publicaties en documenten kunnen inzien, aanpassen, publiceren en intrekken in plaats van dummy data

Afhankelijkheid: de endpoints voor documenten moeten beschikbaar zijn in het ODRC

Acceptatie criteria
- er worden geen dummy publicaties en documenten meer getoond
- de publicaties en documenten die getoond worden komen uit het ODRC
- alleen publicaties en documenten van de ingelogde gebruiker zijn zichtbaar
- Publicaties en documenten worden opgeslagen, geraadpleegd, gemuteerd ~~en verwijderd~~ in het ODRC.

**Tasks**
- [x] Endpoint voor registreren publicatie: mock update verwijderen
- [x] Endpoint voor bijwerken publicatie: aanpassen zodat het verzoek doorgestuurd word aan het ODRC
- [x] Endpoint voor ophalen publicaties van ingelogde gebruiker: aanpassen zodat het verzoek doorgestuurd word aan het ODRC, inclusief filtering
- [x] Endpoint voor ophalen specifieke publicatie: aanpassen zodat het verzoek doorgestuurd word aan het ODRC
- [x] Status >> publicatiestatus
- [x] Filters voor publicaties aanpassen voor ODRC
- [x] Mock voor publicaties opruimen

**Notities**
Op basis van gegevens van ingelogde gebruiker kunnen items worden opgehaald, zie [ODRC story 64](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/69)

**In deze story ook meegenomen:** (zie #42 )
- Check op 'leeg' document (0 bytes)
- Zip mimetypes windows toegevoegd

**Comment by MarcoKlerks** [comment]
💯
